[package]
name = "rs-dlt645"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1"
hex = "0.4"
tokio-serial = "5.4"
tokio-util = "0.7.6"